micronaut:
  application:
    name: mnLegacyDemo
  server:
    port: 8081
hello:
  controller:
    path: "/hello"
  service:
    greeting: "Hello from service"
  config:
    greeting:
      gr: "Χαίρετε"
      en: "Hello"
#JACKSON Properties
jackson:
  #property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
    writeDateTimestampsAsNanoseconds: false
  deserialization:
    failOnUnknownProperties: false
  generator:
    writeNumbersAsStrings: false
    writeBigDecimalAsPlain: false
